import { useEffect, useState } from "react";
import DataStatusTable from "../components/DataStatusTable";
import MetricCard from "../components/MetricCard";
import RegimeBadge from "../components/RegimeBadge";
import { loadCatalog, loadDataStatus, loadDerivedSeries, loadRegimeScore, loadSeries } from "../lib/data";
import { formatSigned } from "../lib/formatters";
import type {
  DataStatusFile,
  DerivedSeriesFile,
  RegimeScoreFile,
  SeriesCatalogEntry,
  TimeSeriesFile
} from "../lib/types";

const overviewSeriesIds = [
  "vix",
  "us10y",
  "net_liquidity",
  "financial_stress",
  "wti_crude",
  "cftc_sp500_lev_money_net"
];

interface OverviewState {
  catalog: SeriesCatalogEntry[];
  regime: RegimeScoreFile;
  status: DataStatusFile;
  series: Array<TimeSeriesFile | DerivedSeriesFile>;
}

function titleCaseBucket(bucket: string) {
  return bucket
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function netLiquidityCatalogEntry(series: DerivedSeriesFile): SeriesCatalogEntry {
  return {
    category: "liquidity",
    frequency: series.frequency,
    higher_is: "supportive",
    id: series.series_id,
    max_stale_days: 14,
    name: "Net liquidity proxy",
    notes: series.method,
    public: true,
    source: series.source,
    source_url: series.source_url,
    units: series.units
  };
}

function catalogEntryForSeries(
  catalog: SeriesCatalogEntry[],
  series: TimeSeriesFile | DerivedSeriesFile
): SeriesCatalogEntry | undefined {
  const catalogEntry = catalog.find((entry) => entry.id === series.series_id);
  if (catalogEntry) return catalogEntry;
  if (series.series_id === "net_liquidity" && "method" in series) return netLiquidityCatalogEntry(series);
  return undefined;
}

export default function Overview() {
  const [data, setData] = useState<OverviewState | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;

    async function loadOverview() {
      try {
        const [catalog, regime, status, series] = await Promise.all([
          loadCatalog(),
          loadRegimeScore(),
          loadDataStatus(),
          Promise.all(
            overviewSeriesIds.map((seriesId) =>
              seriesId === "net_liquidity" ? loadDerivedSeries(seriesId) : loadSeries(seriesId)
            )
          )
        ]);

        if (active) setData({ catalog, regime, status, series });
      } catch (loadError) {
        if (active) setError(loadError instanceof Error ? loadError.message : "Unable to load market data.");
      }
    }

    void loadOverview();

    return () => {
      active = false;
    };
  }, []);

  return (
    <main className="page-shell">
      <section className="page-heading">
        <p className="eyebrow">Market weather</p>
        <h2>Overview</h2>
        <p>Cross-asset conditions summarized from static JSON generated by GitHub Actions.</p>
      </section>
      {error ? <p className="data-error">Data error: {error}</p> : null}
      {data ? (
        <>
          <section className="hero-panel">
            <div>
              <p className="eyebrow">Weather score</p>
              <h3>{data.regime.overall_score.toFixed(2)}</h3>
              <RegimeBadge label={data.regime.label} score={data.regime.overall_score} />
            </div>
            <div className="detail-grid">
              <section>
                <h4>Top supports</h4>
                <ul>
                  {data.regime.top_supports.map((support) => (
                    <li key={support}>{support}</li>
                  ))}
                </ul>
              </section>
              <section>
                <h4>Top risks</h4>
                <ul>
                  {data.regime.top_risks.map((risk) => (
                    <li key={risk}>{risk}</li>
                  ))}
                </ul>
              </section>
            </div>
          </section>
          <section className="panel bucket-panel">
            <div className="section-header">
              <div>
                <p className="eyebrow">Regime inputs</p>
                <h3>Bucket scores</h3>
              </div>
            </div>
            <dl className="bucket-grid">
              {Object.entries(data.regime.buckets).map(([bucket, score]) => (
                <div className="bucket-score" key={bucket}>
                  <dt>{titleCaseBucket(bucket)}</dt>
                  <dd>{formatSigned(score)}</dd>
                </div>
              ))}
            </dl>
          </section>
          <section className="metric-grid" aria-label="Overview metrics">
            {data.series.map((series) => (
              <MetricCard
                catalogEntry={catalogEntryForSeries(data.catalog, series)}
                key={series.series_id}
                series={series}
              />
            ))}
          </section>
          <DataStatusTable seriesIds={overviewSeriesIds} status={data.status} />
        </>
      ) : null}
    </main>
  );
}
