from __future__ import annotations

from datetime import datetime, timezone

from scripts.shared.io import data_dir
from scripts.shared.source_registry import source_registry_entries


def governance(
    provider_id: str,
    score_status: str = "active",
    access_status: str | None = None,
    terms_status: str | None = None,
    citation_notes: str | None = None,
) -> dict[str, object]:
    registry = source_registry_entries()[provider_id]
    return {
        "provider_id": provider_id,
        "access_status": access_status or str(registry["access_status"]),
        "terms_status": terms_status or str(registry["terms_status"]),
        "score_status": score_status,
        "citation_notes": citation_notes or str(registry["notes"]),
    }


CBOE_INDEX_SOURCE_URL = "https://www.cboe.com/us/indices/dashboard/"
CBOE_INDEX_ENDPOINT_BASE = "https://cdn.cboe.com/api/global/us_indices/daily_prices"


TACTICAL_IDS = {
    "vix", "vvix", "vix9d", "vix3m", "high_yield_oas", "investment_grade_oas",
    "bbb_oas", "hy_minus_ig_oas", "broad_dollar", "usdjpy", "eurusd",
    "us2y", "us10y", "us30y", "real_yield_10y", "breakeven_10y",
    "net_liquidity", "reverse_repo", "treasury_general_account", "sofr",
    "cftc_sp500_asset_mgr_net", "cftc_sp500_lev_money_net",
    "put_call_total", "put_call_index", "put_call_equity", "put_call_etp",
    "put_call_vix", "put_call_spx", "put_call_spxw",
    "vx1", "vx2", "vx3", "vx4", "vx5", "vx6", "vx7", "vx8",
    "event_cpi", "event_fomc", "event_payrolls", "event_treasury_auction",
    "event_opex",
}

STRATEGIC_IDS = {
    "real_yield_5y", "real_yield_10y", "breakeven_5y", "breakeven_10y",
    "forward_inflation_5y5y", "cfnai", "cfnai_3m_avg", "real_retail_sales",
    "industrial_production", "durable_goods_orders", "unemployment_rate",
    "nonfarm_payrolls", "initial_claims", "sahm_rule", "headline_cpi",
    "core_cpi", "core_pce", "ppi_final_demand", "bank_credit",
    "loans_and_leases", "business_loans", "bank_deposits", "fed_assets",
    "reserve_balances",
}

REGIME_ROLES_BY_ID = {
    "vix": ["volatility"],
    "vvix": ["tail_risk", "volatility"],
    "vix9d": ["volatility"],
    "vix3m": ["volatility"],
    "us2y": ["nominal_yield"],
    "us10y": ["nominal_yield"],
    "us20y": ["nominal_yield"],
    "us30y": ["nominal_yield"],
    "real_yield_5y": ["real_yield"],
    "real_yield_10y": ["real_yield"],
    "breakeven_5y": ["inflation_expectation"],
    "breakeven_10y": ["inflation_expectation"],
    "forward_inflation_5y5y": ["inflation_expectation"],
    "broad_dollar": ["dollar"],
    "usdjpy": ["dollar"],
    "eurusd": ["dollar"],
    "high_yield_oas": ["credit"],
    "investment_grade_oas": ["credit"],
    "bbb_oas": ["credit"],
    "financial_conditions": ["credit"],
    "financial_stress": ["credit"],
    "net_liquidity": ["liquidity"],
    "fed_assets": ["liquidity"],
    "reverse_repo": ["liquidity"],
    "treasury_general_account": ["liquidity"],
    "reserve_balances": ["liquidity"],
    "sofr": ["liquidity"],
    "wti_crude": ["commodity"],
    "brent_crude": ["commodity"],
    "corn_price": ["commodity"],
    "wheat_price": ["commodity"],
    "soybean_price": ["commodity"],
    "cftc_sp500_asset_mgr_net": ["sentiment"],
    "cftc_sp500_lev_money_net": ["sentiment"],
    "put_call_total": ["sentiment"],
    "put_call_index": ["sentiment"],
    "put_call_equity": ["sentiment"],
    "put_call_etp": ["sentiment"],
    "put_call_vix": ["sentiment", "volatility"],
    "put_call_spx": ["sentiment"],
    "put_call_spxw": ["sentiment"],
    "vx1": ["volatility"],
    "vx2": ["volatility"],
    "vx3": ["volatility"],
    "vx4": ["volatility"],
    "vx5": ["volatility"],
    "vx6": ["volatility"],
    "vx7": ["volatility"],
    "vx8": ["volatility"],
    "event_cpi": ["sentiment"],
    "event_fomc": ["sentiment"],
    "event_payrolls": ["sentiment"],
    "event_treasury_auction": ["sentiment", "liquidity"],
    "event_opex": ["sentiment", "volatility"],
    "cfnai": ["growth"],
    "cfnai_3m_avg": ["growth"],
    "real_retail_sales": ["growth"],
    "industrial_production": ["growth"],
    "durable_goods_orders": ["growth"],
    "unemployment_rate": ["labor"],
    "nonfarm_payrolls": ["labor"],
    "initial_claims": ["labor"],
    "sahm_rule": ["labor"],
    "headline_cpi": ["inflation_expectation"],
    "core_cpi": ["inflation_expectation"],
    "core_pce": ["inflation_expectation"],
    "ppi_final_demand": ["inflation_expectation"],
    "bank_credit": ["banking", "credit"],
    "loans_and_leases": ["banking", "credit"],
    "business_loans": ["banking", "credit"],
    "bank_deposits": ["banking", "liquidity"],
}

PREFERRED_CHART_BY_ROLE = {
    "real_yield": "decomposition",
    "nominal_yield": "decomposition",
    "inflation_expectation": "decomposition",
    "volatility": "curve",
    "dollar": "line",
    "credit": "line",
    "liquidity": "line",
    "growth": "line",
    "labor": "line",
    "commodity": "line",
    "sentiment": "line",
    "tail_risk": "line",
    "banking": "line",
}


def decision_metadata(series_id: str, category: str) -> dict[str, object]:
    tactical = series_id in TACTICAL_IDS
    strategic = series_id in STRATEGIC_IDS
    if tactical and strategic:
        horizon = "both"
    elif tactical:
        horizon = "tactical"
    elif strategic:
        horizon = "strategic"
    else:
        horizon = "strategic" if category in {"growth", "labor", "inflation", "banking"} else "tactical"
    roles = REGIME_ROLES_BY_ID.get(series_id, [category])
    return {
        "horizon": horizon,
        "regime_role": roles,
        "preferred_chart": PREFERRED_CHART_BY_ROLE.get(str(roles[0]), "line"),
    }


def cboe_index_series(
    series_id: str,
    name: str,
    filename: str,
    value_columns: tuple[str, ...],
    notes: str,
) -> dict[str, object]:
    return {
        "id": series_id,
        "name": name,
        "category": "volatility",
        "source": "Cboe",
        "source_url": CBOE_INDEX_SOURCE_URL,
        "endpoint_url": f"{CBOE_INDEX_ENDPOINT_BASE}/{filename}",
        "value_columns": value_columns,
        "frequency": "daily",
        "units": "index",
        "higher_is": "riskier",
        "public": True,
        "max_stale_days": 7,
        "notes": notes,
        **decision_metadata(series_id, "volatility"),
        **governance(
            "cboe",
            citation_notes="Cboe public historical index data; displayed with source caveats.",
        ),
    }


CBOE_VIX = cboe_index_series(
    "vix",
    "Cboe Volatility Index",
    "VIX_History.csv",
    ("CLOSE", "VIX"),
    "Daily VIX close from Cboe public historical data.",
)

CBOE_INDEX_SERIES = [
    CBOE_VIX,
    cboe_index_series(
        "vvix",
        "Cboe VIX Volatility Index",
        "VVIX_History.csv",
        ("CLOSE", "VVIX"),
        "Daily VVIX close from Cboe public historical data.",
    ),
    cboe_index_series(
        "vix9d",
        "Cboe 9-Day Volatility Index",
        "VIX9D_History.csv",
        ("CLOSE", "VIX9D"),
        "Daily VIX9D close from Cboe public historical data.",
    ),
    cboe_index_series(
        "vix3m",
        "Cboe 3-Month Volatility Index",
        "VIX3M_History.csv",
        ("CLOSE", "VIX3M"),
        "Daily VIX3M close from Cboe public historical data.",
    ),
]


FRED_SERIES = [
    {
        "id": "us2y",
        "fred_id": "DGS2",
        "name": "2-Year Treasury Constant Maturity Rate",
        "category": "rates",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily 2-year Treasury yield from FRED.",
    },
    {
        "id": "us10y",
        "fred_id": "DGS10",
        "name": "10-Year Treasury Constant Maturity Rate",
        "category": "rates",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily 10-year Treasury yield from FRED.",
    },
    {
        "id": "us20y",
        "fred_id": "DGS20",
        "name": "20-Year Treasury Constant Maturity Rate",
        "category": "rates",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily 20-year Treasury yield from FRED.",
    },
    {
        "id": "us30y",
        "fred_id": "DGS30",
        "name": "30-Year Treasury Constant Maturity Rate",
        "category": "rates",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily 30-year Treasury yield from FRED.",
    },
    {
        "id": "fed_assets",
        "fred_id": "WALCL",
        "name": "Federal Reserve Total Assets",
        "category": "liquidity",
        "frequency": "weekly",
        "units": "millions_usd",
        "higher_is": "supportive",
        "max_stale_days": 14,
        "notes": "Weekly Federal Reserve balance sheet assets from FRED.",
    },
    {
        "id": "reverse_repo",
        "fred_id": "RRPONTSYD",
        "name": "Overnight Reverse Repurchase Agreements",
        "category": "liquidity",
        "frequency": "daily",
        "units": "billions_usd",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily reverse repo operations from FRED.",
    },
    {
        "id": "treasury_general_account",
        "fred_id": "WTREGEN",
        "name": "Treasury General Account",
        "category": "liquidity",
        "frequency": "weekly",
        "units": "millions_usd",
        "higher_is": "riskier",
        "max_stale_days": 14,
        "notes": "Weekly Treasury General Account balance from FRED.",
    },
    {
        "id": "sofr",
        "fred_id": "SOFR",
        "name": "Secured Overnight Financing Rate",
        "category": "liquidity",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily SOFR from FRED.",
    },
    {
        "id": "financial_stress",
        "fred_id": "STLFSI4",
        "name": "St. Louis Fed Financial Stress Index",
        "category": "credit",
        "frequency": "weekly",
        "units": "index",
        "higher_is": "riskier",
        "max_stale_days": 14,
        "notes": "Weekly financial stress index published by the St. Louis Fed.",
    },
    {
        "id": "financial_conditions",
        "fred_id": "NFCI",
        "name": "Chicago Fed National Financial Conditions Index",
        "category": "credit",
        "frequency": "weekly",
        "units": "index",
        "higher_is": "riskier",
        "max_stale_days": 14,
        "notes": "Weekly national financial conditions index published by the Chicago Fed.",
    },
    {
        "id": "wti_crude",
        "fred_id": "DCOILWTICO",
        "name": "WTI Crude Oil Spot Price",
        "category": "commodities",
        "frequency": "daily",
        "units": "usd_per_barrel",
        "higher_is": "riskier",
        "max_stale_days": 10,
        "notes": "Daily WTI crude oil spot price from FRED graph CSV.",
    },
    {
        "id": "brent_crude",
        "fred_id": "DCOILBRENTEU",
        "name": "Brent Crude Oil Spot Price",
        "category": "commodities",
        "frequency": "daily",
        "units": "usd_per_barrel",
        "higher_is": "riskier",
        "max_stale_days": 10,
        "notes": "Daily Brent crude oil spot price from FRED graph CSV.",
    },
    {
        "id": "corn_price",
        "fred_id": "PMAIZMTUSDM",
        "name": "Global Corn Price",
        "category": "commodities",
        "frequency": "monthly",
        "units": "usd_per_metric_ton",
        "higher_is": "riskier",
        "max_stale_days": 75,
        "notes": "Monthly global corn price from FRED graph CSV.",
    },
    {
        "id": "wheat_price",
        "fred_id": "PWHEAMTUSDM",
        "name": "Global Wheat Price",
        "category": "commodities",
        "frequency": "monthly",
        "units": "usd_per_metric_ton",
        "higher_is": "riskier",
        "max_stale_days": 75,
        "notes": "Monthly global wheat price from FRED graph CSV.",
    },
    {
        "id": "soybean_price",
        "fred_id": "PSOYBUSDM",
        "name": "Global Soybean Price",
        "category": "commodities",
        "frequency": "monthly",
        "units": "usd_per_metric_ton",
        "higher_is": "riskier",
        "max_stale_days": 75,
        "notes": "Monthly global soybean price from FRED graph CSV.",
    },
    {
        "id": "high_yield_oas",
        "fred_id": "BAMLH0A0HYM2",
        "name": "ICE BofA US High Yield Option-Adjusted Spread",
        "category": "credit",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily high-yield option-adjusted spread from FRED graph CSV.",
        "citation_notes": "Active via FRED graph CSV; source-specific citation and terms review required for ICE BofA OAS data.",
    },
    {
        "id": "investment_grade_oas",
        "fred_id": "BAMLC0A0CM",
        "name": "ICE BofA US Corporate Option-Adjusted Spread",
        "category": "credit",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily investment-grade corporate option-adjusted spread from FRED graph CSV.",
        "citation_notes": "Active via FRED graph CSV; source-specific citation and terms review required for ICE BofA OAS data.",
    },
    {
        "id": "bbb_oas",
        "fred_id": "BAMLC0A4CBBB",
        "name": "ICE BofA BBB US Corporate Option-Adjusted Spread",
        "category": "credit",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily BBB corporate option-adjusted spread from FRED graph CSV.",
        "citation_notes": "Active via FRED graph CSV; source-specific citation and terms review required for ICE BofA OAS data.",
    },
    {
        "id": "real_yield_10y",
        "fred_id": "DFII10",
        "name": "10-Year Treasury Inflation-Indexed Security Real Yield",
        "category": "rates",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "contextual",
        "max_stale_days": 7,
        "notes": "Daily 10-year Treasury real yield from FRED graph CSV.",
    },
    {
        "id": "real_yield_5y",
        "fred_id": "DFII5",
        "name": "5-Year Treasury Inflation-Indexed Security Real Yield",
        "category": "rates",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "contextual",
        "max_stale_days": 7,
        "notes": "Daily 5-year Treasury real yield from FRED graph CSV.",
    },
    {
        "id": "breakeven_10y",
        "fred_id": "T10YIE",
        "name": "10-Year Breakeven Inflation Rate",
        "category": "inflation",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily 10-year breakeven inflation rate from FRED graph CSV.",
    },
    {
        "id": "breakeven_5y",
        "fred_id": "T5YIE",
        "name": "5-Year Breakeven Inflation Rate",
        "category": "inflation",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily 5-year breakeven inflation rate from FRED graph CSV.",
    },
    {
        "id": "forward_inflation_5y5y",
        "fred_id": "T5YIFR",
        "name": "5-Year, 5-Year Forward Inflation Expectation Rate",
        "category": "inflation",
        "frequency": "daily",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 7,
        "notes": "Daily 5-year, 5-year forward inflation expectation rate from FRED graph CSV.",
    },
    {
        "id": "cfnai",
        "fred_id": "CFNAI",
        "name": "Chicago Fed National Activity Index",
        "category": "growth",
        "frequency": "monthly",
        "units": "index",
        "higher_is": "supportive",
        "max_stale_days": 45,
        "notes": "Monthly Chicago Fed National Activity Index from FRED graph CSV.",
    },
    {
        "id": "cfnai_3m_avg",
        "fred_id": "CFNAIMA3",
        "name": "Chicago Fed National Activity Index 3-Month Moving Average",
        "category": "growth",
        "frequency": "monthly",
        "units": "index",
        "higher_is": "supportive",
        "max_stale_days": 45,
        "notes": "Monthly CFNAI 3-month moving average from FRED graph CSV.",
    },
    {
        "id": "real_retail_sales",
        "fred_id": "RRSFS",
        "name": "Real Retail and Food Services Sales",
        "category": "growth",
        "frequency": "monthly",
        "units": "millions_chained_2017_usd",
        "higher_is": "supportive",
        "max_stale_days": 45,
        "notes": "Monthly real retail and food services sales from FRED graph CSV.",
    },
    {
        "id": "industrial_production",
        "fred_id": "INDPRO",
        "name": "Industrial Production Index",
        "category": "growth",
        "frequency": "monthly",
        "units": "index",
        "higher_is": "supportive",
        "max_stale_days": 45,
        "notes": "Monthly industrial production index from FRED graph CSV.",
    },
    {
        "id": "durable_goods_orders",
        "fred_id": "DGORDER",
        "name": "Manufacturers' New Orders: Durable Goods",
        "category": "growth",
        "frequency": "monthly",
        "units": "millions_usd",
        "higher_is": "supportive",
        "max_stale_days": 45,
        "notes": "Monthly durable goods orders from FRED graph CSV.",
    },
    {
        "id": "unemployment_rate",
        "fred_id": "UNRATE",
        "name": "Unemployment Rate",
        "category": "labor",
        "frequency": "monthly",
        "units": "percent",
        "higher_is": "riskier",
        "max_stale_days": 45,
        "notes": "Monthly unemployment rate from FRED graph CSV.",
    },
    {
        "id": "nonfarm_payrolls",
        "fred_id": "PAYEMS",
        "name": "All Employees, Total Nonfarm",
        "category": "labor",
        "frequency": "monthly",
        "units": "thousands",
        "higher_is": "supportive",
        "max_stale_days": 45,
        "notes": "Monthly nonfarm payroll employment level from FRED graph CSV.",
    },
    {
        "id": "initial_claims",
        "fred_id": "ICSA",
        "name": "Initial Claims",
        "category": "labor",
        "frequency": "weekly",
        "units": "number",
        "higher_is": "riskier",
        "max_stale_days": 14,
        "notes": "Weekly initial unemployment insurance claims from FRED graph CSV.",
    },
    {
        "id": "sahm_rule",
        "fred_id": "SAHMREALTIME",
        "name": "Real-Time Sahm Rule Recession Indicator",
        "category": "labor",
        "frequency": "monthly",
        "units": "percentage_points",
        "higher_is": "riskier",
        "max_stale_days": 45,
        "notes": "Monthly real-time Sahm Rule recession indicator from FRED graph CSV.",
    },
    {
        "id": "headline_cpi",
        "fred_id": "CPIAUCSL",
        "name": "Consumer Price Index for All Urban Consumers",
        "category": "inflation",
        "frequency": "monthly",
        "units": "index",
        "higher_is": "riskier",
        "max_stale_days": 45,
        "notes": "Monthly headline CPI index from FRED graph CSV.",
    },
    {
        "id": "core_cpi",
        "fred_id": "CPILFESL",
        "name": "Consumer Price Index Less Food and Energy",
        "category": "inflation",
        "frequency": "monthly",
        "units": "index",
        "higher_is": "riskier",
        "max_stale_days": 45,
        "notes": "Monthly core CPI index from FRED graph CSV.",
    },
    {
        "id": "core_pce",
        "fred_id": "PCEPILFE",
        "name": "Core Personal Consumption Expenditures Price Index",
        "category": "inflation",
        "frequency": "monthly",
        "units": "index",
        "higher_is": "riskier",
        "max_stale_days": 45,
        "notes": "Monthly core PCE price index from FRED graph CSV.",
    },
    {
        "id": "ppi_final_demand",
        "fred_id": "PPIFIS",
        "name": "Producer Price Index by Commodity: Final Demand",
        "category": "inflation",
        "frequency": "monthly",
        "units": "index",
        "higher_is": "riskier",
        "max_stale_days": 45,
        "notes": "Monthly PPI final demand index from FRED graph CSV.",
    },
    {
        "id": "broad_dollar",
        "fred_id": "DTWEXBGS",
        "name": "Nominal Broad U.S. Dollar Index",
        "category": "dollar",
        "frequency": "daily",
        "units": "index",
        "higher_is": "contextual",
        "max_stale_days": 7,
        "notes": "Daily broad U.S. dollar index from FRED graph CSV.",
    },
    {
        "id": "usdjpy",
        "fred_id": "DEXJPUS",
        "name": "Japanese Yen to U.S. Dollar Exchange Rate",
        "category": "dollar",
        "frequency": "daily",
        "units": "jpy_per_usd",
        "higher_is": "contextual",
        "max_stale_days": 7,
        "notes": "Daily USD/JPY exchange rate from FRED graph CSV.",
    },
    {
        "id": "eurusd",
        "fred_id": "DEXUSEU",
        "name": "U.S. Dollars to Euro Exchange Rate",
        "category": "dollar",
        "frequency": "daily",
        "units": "usd_per_eur",
        "higher_is": "contextual",
        "max_stale_days": 7,
        "notes": "Daily EUR/USD exchange rate from FRED graph CSV.",
    },
    {
        "id": "reserve_balances",
        "fred_id": "WRESBAL",
        "name": "Reserve Balances with Federal Reserve Banks",
        "category": "liquidity",
        "frequency": "weekly",
        "units": "millions_usd",
        "higher_is": "supportive",
        "max_stale_days": 14,
        "notes": "Weekly reserve balances with Federal Reserve Banks from FRED graph CSV.",
    },
    {
        "id": "bank_credit",
        "fred_id": "TOTBKCR",
        "name": "Bank Credit, All Commercial Banks",
        "category": "credit",
        "frequency": "weekly",
        "units": "billions_usd",
        "higher_is": "supportive",
        "max_stale_days": 14,
        "notes": "Weekly bank credit from FRED graph CSV.",
    },
    {
        "id": "loans_and_leases",
        "fred_id": "TOTLL",
        "name": "Loans and Leases in Bank Credit",
        "category": "credit",
        "frequency": "weekly",
        "units": "billions_usd",
        "higher_is": "supportive",
        "max_stale_days": 14,
        "notes": "Weekly loans and leases in bank credit from FRED graph CSV.",
    },
    {
        "id": "business_loans",
        "fred_id": "BUSLOANS",
        "name": "Commercial and Industrial Loans",
        "category": "credit",
        "frequency": "weekly",
        "units": "billions_usd",
        "higher_is": "supportive",
        "max_stale_days": 14,
        "notes": "Weekly commercial and industrial loans from FRED graph CSV.",
    },
    {
        "id": "bank_deposits",
        "fred_id": "DPSACBW027SBOG",
        "name": "Deposits, All Commercial Banks",
        "category": "liquidity",
        "frequency": "weekly",
        "units": "billions_usd",
        "higher_is": "supportive",
        "max_stale_days": 14,
        "notes": "Weekly commercial bank deposits from FRED graph CSV.",
    },
]


CFTC_SOURCE_URL = "https://www.cftc.gov/MarketReports/CommitmentsofTraders/HistoricalCompressed/index.htm"

CFTC_POSITIONING_SERIES = [
    {
        "id": "cftc_sp500_asset_mgr_net",
        "name": "CFTC E-mini S&P 500 Asset Manager Net Positioning",
        "category": "sentiment",
        "frequency": "weekly",
        "units": "percent_open_interest",
        "higher_is": "contextual",
        "max_stale_days": 14,
        "notes": "Asset manager long minus short positioning as percent of open interest from CFTC Traders in Financial Futures.",
    },
    {
        "id": "cftc_sp500_lev_money_net",
        "name": "CFTC E-mini S&P 500 Leveraged Money Net Positioning",
        "category": "sentiment",
        "frequency": "weekly",
        "units": "percent_open_interest",
        "higher_is": "riskier",
        "max_stale_days": 14,
        "notes": "Leveraged money long minus short positioning as percent of open interest from CFTC Traders in Financial Futures.",
    },
]


def tactical_candidate_series(
    series_id: str,
    name: str,
    category: str,
    source: str,
    source_url: str,
    frequency: str,
    units: str,
    max_stale_days: int,
    notes: str,
    provider_id: str,
    higher_is: str = "contextual",
) -> dict[str, object]:
    return {
        "id": series_id,
        "name": name,
        "category": category,
        "source": source,
        "source_url": source_url,
        "endpoint_url": None,
        "frequency": frequency,
        "units": units,
        "higher_is": higher_is,
        "public": False,
        "max_stale_days": max_stale_days,
        "notes": notes,
        **governance(provider_id, score_status="candidate"),
    }


PUT_CALL_SOURCE_URL = "https://www.cboe.com/markets/us/options/market_statistics/"
VIX_FUTURES_SOURCE_URL = "https://www.cboe.com/us/futures/"


PUT_CALL_CANDIDATE_SERIES = [
    tactical_candidate_series(
        "put_call_total",
        "Total Put/Call Ratio",
        "sentiment",
        "Cboe Options Market Statistics",
        PUT_CALL_SOURCE_URL,
        "daily",
        "ratio",
        7,
        "Candidate total put/call options ratio; requires terms review before automated ingestion.",
        "cboe_options",
    ),
    tactical_candidate_series(
        "put_call_index",
        "Index Put/Call Ratio",
        "sentiment",
        "Cboe Options Market Statistics",
        PUT_CALL_SOURCE_URL,
        "daily",
        "ratio",
        7,
        "Candidate index options put/call ratio; requires terms review before automated ingestion.",
        "cboe_options",
    ),
    tactical_candidate_series(
        "put_call_equity",
        "Equity Put/Call Ratio",
        "sentiment",
        "Cboe Options Market Statistics",
        PUT_CALL_SOURCE_URL,
        "daily",
        "ratio",
        7,
        "Candidate equity options put/call ratio; requires terms review before automated ingestion.",
        "cboe_options",
    ),
    tactical_candidate_series(
        "put_call_etp",
        "ETP Put/Call Ratio",
        "sentiment",
        "Cboe Options Market Statistics",
        PUT_CALL_SOURCE_URL,
        "daily",
        "ratio",
        7,
        "Candidate ETP options put/call ratio; requires terms review before automated ingestion.",
        "cboe_options",
    ),
    tactical_candidate_series(
        "put_call_vix",
        "VIX Options Put/Call Ratio",
        "sentiment",
        "Cboe Options Market Statistics",
        PUT_CALL_SOURCE_URL,
        "daily",
        "ratio",
        7,
        "Candidate VIX options put/call ratio; requires terms review before automated ingestion.",
        "cboe_options",
    ),
    tactical_candidate_series(
        "put_call_spx",
        "SPX Options Put/Call Ratio",
        "sentiment",
        "Cboe Options Market Statistics",
        PUT_CALL_SOURCE_URL,
        "daily",
        "ratio",
        7,
        "Candidate SPX options put/call ratio; requires terms review before automated ingestion.",
        "cboe_options",
    ),
    tactical_candidate_series(
        "put_call_spxw",
        "SPXW Options Put/Call Ratio",
        "sentiment",
        "Cboe Options Market Statistics",
        PUT_CALL_SOURCE_URL,
        "daily",
        "ratio",
        7,
        "Candidate SPXW weekly options put/call ratio; requires terms review before automated ingestion.",
        "cboe_options",
    ),
]


VIX_FUTURES_CANDIDATE_SERIES = [
    tactical_candidate_series(
        f"vx{tenor}",
        f"VIX Futures Month {tenor}",
        "volatility",
        "Cboe Futures Exchange",
        VIX_FUTURES_SOURCE_URL,
        "daily",
        "index_points",
        7,
        f"Candidate VIX futures curve tenor VX{tenor}; requires access and redistribution review before automated ingestion.",
        "cboe_futures",
    )
    for tenor in range(1, 9)
]


EVENT_RISK_CANDIDATE_SERIES = [
    tactical_candidate_series(
        "event_cpi",
        "CPI Release Event Risk",
        "sentiment",
        "Economic Release Calendar",
        "",
        "calendar",
        "event",
        45,
        "Candidate CPI release event-risk calendar row; requires source review before automated publication.",
        "economic_calendar",
    ),
    tactical_candidate_series(
        "event_fomc",
        "FOMC Meeting Event Risk",
        "sentiment",
        "Economic Release Calendar",
        "",
        "calendar",
        "event",
        45,
        "Candidate FOMC meeting event-risk calendar row; requires source review before automated publication.",
        "economic_calendar",
    ),
    tactical_candidate_series(
        "event_payrolls",
        "Payrolls Release Event Risk",
        "sentiment",
        "Economic Release Calendar",
        "",
        "calendar",
        "event",
        45,
        "Candidate payrolls release event-risk calendar row; requires source review before automated publication.",
        "economic_calendar",
    ),
    tactical_candidate_series(
        "event_treasury_auction",
        "Treasury Auction Event Risk",
        "sentiment",
        "Treasury Auction Calendar",
        "",
        "calendar",
        "event",
        45,
        "Candidate Treasury auction event-risk calendar row; requires source review before automated publication.",
        "treasury_calendar",
    ),
    tactical_candidate_series(
        "event_opex",
        "Options Expiration Event Risk",
        "sentiment",
        "Economic Release Calendar",
        "",
        "calendar",
        "event",
        45,
        "Candidate options expiration event-risk calendar row; requires source review before automated publication.",
        "economic_calendar",
    ),
]


CANDIDATE_SERIES = [
    {
        "id": "ism_manufacturing_pmi",
        "name": "ISM Manufacturing PMI",
        "category": "growth",
        "source": "ISM",
        "source_url": "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-pmi-reports/",
        "endpoint_url": None,
        "frequency": "monthly",
        "units": "index",
        "higher_is": "contextual",
        "public": False,
        "max_stale_days": 45,
        "notes": "Candidate fast growth input; requires terms and redistribution review before automated ingestion.",
        **governance("terms_review", score_status="candidate"),
    },
    {
        "id": "move_index",
        "name": "MOVE Index",
        "category": "volatility",
        "source": "ICE",
        "source_url": "https://developer.ice.com/fixed-income-data-services/catalog/ice-data-indices-move-index",
        "endpoint_url": None,
        "frequency": "daily",
        "units": "index",
        "higher_is": "riskier",
        "public": False,
        "max_stale_days": 7,
        "notes": "Candidate Treasury volatility input; not active because automated access and redistribution need review.",
        **governance("terms_review", score_status="candidate"),
    },
    *PUT_CALL_CANDIDATE_SERIES,
    *VIX_FUTURES_CANDIDATE_SERIES,
    *EVENT_RISK_CANDIDATE_SERIES,
]


def fred_endpoint(fred_id: str) -> str:
    return f"https://fred.stlouisfed.org/graph/fredgraph.csv?id={fred_id}"


def cftc_tff_year_url(year: int) -> str:
    return f"https://www.cftc.gov/files/dea/history/fut_fin_txt_{year}.zip"


def catalog_entries() -> list[dict[str, object]]:
    entries = [series.copy() for series in CBOE_INDEX_SERIES]
    for series in FRED_SERIES:
        entries.append(
            {
                "id": series["id"],
                "name": series["name"],
                "category": series["category"],
                "source": "FRED",
                "source_url": f"https://fred.stlouisfed.org/series/{series['fred_id']}",
                "endpoint_url": fred_endpoint(str(series["fred_id"])),
                "frequency": series["frequency"],
                "units": series["units"],
                "higher_is": series["higher_is"],
                "public": True,
                "max_stale_days": series["max_stale_days"],
                "notes": series["notes"],
                **decision_metadata(str(series["id"]), str(series["category"])),
                **governance(
                    "fred",
                    score_status=str(series.get("score_status", "active")),
                    access_status=str(series.get("access_status", "free_public")),
                    terms_status=str(series.get("terms_status", "review_each_series")),
                    citation_notes=str(series.get("citation_notes", "FRED graph CSV endpoint; review source-specific citation and copyright fields.")),
                ),
            }
        )
    for series in CFTC_POSITIONING_SERIES:
        entries.append(
            {
                "id": series["id"],
                "name": series["name"],
                "category": series["category"],
                "source": "CFTC",
                "source_url": CFTC_SOURCE_URL,
                "endpoint_url": cftc_tff_year_url(datetime.now(timezone.utc).year),
                "frequency": series["frequency"],
                "units": series["units"],
                "higher_is": series["higher_is"],
                "public": True,
                "max_stale_days": series["max_stale_days"],
                "notes": series["notes"],
                **decision_metadata(str(series["id"]), str(series["category"])),
                **governance("cftc", citation_notes="Public CFTC historical compressed report transformed into derived positioning context."),
            }
        )
    entries.extend(
        [
            {
                **series,
                **decision_metadata(str(series["id"]), str(series["category"])),
            }
            for series in CANDIDATE_SERIES
        ]
    )
    return entries


def available_catalog_entries() -> list[dict[str, object]]:
    series_dir = data_dir() / "series"
    return [
        entry
        for entry in catalog_entries()
        if (series_dir / f"{entry['id']}.json").exists()
        and entry.get("score_status") == "active"
        and entry.get("public") is True
    ]
