from __future__ import annotations


def source_registry_entries() -> dict[str, dict[str, object]]:
    return {
        "fred": {
            "name": "Federal Reserve Economic Data",
            "base_url": "https://fred.stlouisfed.org",
            "requires_secret": False,
            "access_status": "free_public",
            "terms_status": "review_each_series",
            "update_cadence": "varies_by_series",
            "notes": "FRED graph CSV endpoints do not require secrets; hosted series can carry source-specific citation or redistribution requirements.",
        },
        "cboe": {
            "name": "Cboe Global Markets",
            "base_url": "https://www.cboe.com",
            "requires_secret": False,
            "access_status": "free_public",
            "terms_status": "ok",
            "update_cadence": "daily_market_data",
            "notes": "Cboe historical index CSV files are public and delayed; source caveats should be shown with the data.",
        },
        "cboe_options": {
            "name": "Cboe Options Market Statistics",
            "base_url": "https://www.cboe.com/markets/us/options/market_statistics/",
            "requires_secret": False,
            "access_status": "terms_review_needed",
            "terms_status": "review_needed",
            "update_cadence": "daily_market_data",
            "notes": "Put-call data requires access, automation, attribution, and redistribution review before automated publication.",
        },
        "ice_indices": {
            "name": "ICE Data Indices",
            "base_url": "https://developer.ice.com/fixed-income-data-services/",
            "requires_secret": False,
            "access_status": "terms_review_needed",
            "terms_status": "review_needed",
            "update_cadence": "daily_market_data",
            "notes": "MOVE Index access and static redistribution require source review before active ingestion.",
        },
        "occ": {
            "name": "Options Clearing Corporation",
            "base_url": "https://www.theocc.com",
            "requires_secret": False,
            "access_status": "terms_review_needed",
            "terms_status": "review_needed",
            "update_cadence": "daily_market_data",
            "notes": "Options statistics require source-specific access, citation, and redistribution review before automated publication.",
        },
        "cboe_futures": {
            "name": "Cboe Futures Exchange",
            "base_url": "https://www.cboe.com/us/futures/",
            "requires_secret": False,
            "access_status": "terms_review_needed",
            "terms_status": "review_needed",
            "update_cadence": "daily_market_data",
            "notes": "VIX futures curve data requires access and redistribution review before automated publication.",
        },
        "cftc": {
            "name": "U.S. Commodity Futures Trading Commission",
            "base_url": "https://www.cftc.gov",
            "requires_secret": False,
            "access_status": "free_public",
            "terms_status": "ok",
            "update_cadence": "weekly",
            "notes": "Public historical compressed Commitments of Traders reports.",
        },
        "derived": {
            "name": "Derived",
            "base_url": "/data",
            "requires_secret": False,
            "access_status": "free_public",
            "terms_status": "ok",
            "update_cadence": "after_source_updates",
            "notes": "Computed from active public inputs in this repository.",
        },
        "economic_calendar": {
            "name": "Economic Release Calendar",
            "base_url": "",
            "requires_secret": False,
            "access_status": "terms_review_needed",
            "terms_status": "review_needed",
            "update_cadence": "calendar",
            "notes": "Economic calendar sources require access, attribution, automation, and redistribution review before automated publication.",
        },
        "treasury_calendar": {
            "name": "Treasury Auction Calendar",
            "base_url": "",
            "requires_secret": False,
            "access_status": "terms_review_needed",
            "terms_status": "review_needed",
            "update_cadence": "calendar",
            "notes": "Treasury auction schedules require source-specific access, attribution, and redistribution review before automated publication.",
        },
        "fiscaldata": {
            "name": "U.S. Treasury FiscalData",
            "base_url": "https://fiscaldata.treasury.gov",
            "requires_secret": False,
            "access_status": "free_public",
            "terms_status": "review_each_series",
            "update_cadence": "monthly_or_auction_calendar",
            "notes": "Official Treasury FiscalData API paths can be generated into static candidate diagnostics with dataset attribution.",
        },
        "terms_review": {
            "name": "Terms-reviewed candidate sources",
            "base_url": "",
            "requires_secret": False,
            "access_status": "terms_review_needed",
            "terms_status": "review_needed",
            "update_cadence": "not_active",
            "notes": "Useful sources that require access, terms, licensing, citation, or redistribution review before automated publication.",
        },
        "unavailable": {
            "name": "Unavailable or restricted sources",
            "base_url": "",
            "requires_secret": True,
            "access_status": "unavailable",
            "terms_status": "restricted",
            "update_cadence": "not_active",
            "notes": "Sources that are not freely automatable for this static no-secret project.",
        },
    }
